### ISSUE TITLE
ATS100 flash not working

### ISSUE THREAD

**Issue by jcm4atx** [jeffmer/SI4732_Espruino#2]
I have an ATS100. I'm following the instructions in `README_flash.txt`.  This is what I get...

```
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP32
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 40:22:d8:08:8d:7c
Changing baud rate to 921600
Changed.
Enabling default SPI flash mode...

A fatal error occurred: Failed to configure SPI flash pins. Only got 3 byte status response.
```

And it bricks my radio. Now I am able to recover. I keep trying, but get the same error.

**Comment by jcm4atx** [comment]
I found my problem. I ran `stty -F /dev/ttyUSB0 -a` and discovered my baud rate is 115200. I changed the baud rate in my command to match this and it worked.

**Comment by jeffmer** [comment]
Glad that worked. I was going to suggest lowering the baud rate.
